dist: trusty
sudo: false
language: elixir
elixir:
  - 1.7.1
otp_release:
  - 21.0

env:
  - MIX_ENV=test VERBOSE_TEST=true

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

branches:
  only:
    - master
