dist: trusty
sudo: required
language: elixir
elixir:
  - 1.7.1
otp_release:
  - 21.0
addons:
  postgresql: '10.4'
services:
  - postgresql
env:
  - MIX_ENV=test VERBOSE_TEST=true

script:
  - mix ecto.setup
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

branches:
  only:
    - master
    - /^v[\d.]+/
